version: "3"

networks:
  loki:

services:
#  app:
#    build: .
#    restart: always
#    ports:
#      - "5001:5001"

  loki:
    image: grafana/loki:main
    container_name: loki-service
    ports:
      - "3100:3100"
    volumes:
      - "./etc/loki:/mnt/config"
    command: -config.file=/mnt/config/loki-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:main
    container_name: promtail-service
    volumes:
      - "./etc/promtail:/mnt/config"
      - "/var/lib/docker/containers:/var/lib/docker/containers"
    command: -config.file=/mnt/config/promtail-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-service
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - loki