version: "3"

networks:
  loki:

services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "5001:5001"

  loki:
    image: grafana/loki:main
    container_name: loki-service
    ports:
      - "3100:3100"
    volumes:
      - "./loki:/mnt/configs"
    command: -configs.file=/mnt/configs/loki-configs.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-service
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - loki