server:
  port: 8080
  url-prefix: api
  api-version: v1

mysql:
  uri: 'root:123456@tcp(127.0.0.1:3306)/evetion?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  table-prefix: sys
  no-sql: false
  init-data: true
  transaction: true